stages:
  - build_env
  - syntax_check

cache:
  paths:
    - telemetry/
  policy: pull-push

build_environment:
  stage: build_env
  tags:
  - build_env
  script:
  - sudo apt-get update && sudo apt-get upgrade -y
  - sudo apt-get install python3-pip -y
  - sudo pip3 install --upgrade pip
  - sudo pip3 install virtualenv
  - virtualenv telemetry
  - source telemetry/bin/activate
  - sudo pip3 install yamllint
  - sudo pip3 install pylint
  - sudo pip3 install jinja2
  - sudo pip3 install credPass
  - sudo pip3 install influxdb
  - sudo apt-get install npm -y
  - sudo apt-get install nodejs-legacy -y
  - sudo npm install jsonlint -g

syntax_check:
  stage: syntax_check
  tags:
  - syntax_check
  script:
  - source telemetry/bin/activate
  # - yamllint tcp-probes/var/
  - yamllint ping-probes/var/
  # - pylint --const-rgx='[a-z_][a-z0-9_]{2,30}$' tcp-probes/*.py
  - pylint --const-rgx='[a-z_][a-z0-9_]{2,30}$' ping-probes/*.py
  # - jsonlint tcp-probes/*.json
  - jsonlint ping-probes/.credentials.json
  - sudo wget https://github.com/hadolint/hadolint/releases/download/v1.13.0/hadolint-Linux-x86_64 -o hadolint && sudo chmod +x hadolint
  - ./hadolint Dockerfile
